site_name: My User Guides
nav:
  - Home: index.md
  - About: about.md
  - User Guides: guides.md
nav:
  - Home: index.md
  - Git:
    - Intro to Git for Technical Writers: git/intro-git-technical-writers.md
    - Merge Branches with Tortoise Git: git/merge-branches-tortoise-git.md
    - Generate and Use SSH Keys with TortoiseGit: git/create-ssh-keys-tortoise-git.md
    - Resolve Merge Conflicts with TortoiseGit: git/merge-conflicts-tortoise-git.md
theme: readthedocs
site_url: "https://jordansmkdocssite.netlify.app"
use_directory_urls: false
plugins: []