site_name: MkLorum
nav:
  - Home: index.md
  - About: about.md
  - User Guides: guides.md
nav:
  - Home: index.md
  - User Guide:
    - Intro to Git for Technical Writers: intro-git-technical-writers.md
    - Merge Branches with Tortoise Git: merge-branches-tortoise-git.md
    - Generate and Use SSH Keys with TortoiseGit: create-ssh-keys-tortoise-git.md
  - About:
    - License: license.md
    - Release Notes: release-notes.md
theme: readthedocs
site_url: ""
use_directory_urls: false
plugins: []